### ISSUE TITLE
Duplicate dependency check is failing incorrectly on pg_shdepend

### ISSUE THREAD

**Issue by zubeyr94** [EnterpriseDB/pg_catcheck#9]
After the change in https://github.com/EnterpriseDB/pg_catcheck/commit/5d3bfc8d8771f6a5d8897748e07e50badeed25fb, pg_catcheck started to read the rows one by one for some catalogs including pg_shdepend. However, tool is still creating hash tables on these catalogs to do duplicate owner check here: https://github.com/EnterpriseDB/pg_catcheck/blob/master/check_depend.c#L346-L349. Hash table stores the rownum as the key, however rownum for tables loaded by singlerow will always be 0. This causes conflicts and incorrect inconsistencies on pg_shdepend.

**Comment by robertmhaas** [comment]
Sorry, I only just saw this. Thanks for the report; we'll run this down.

**Comment by rhaas-edb** [comment]
Can you describe how to reproduce this issue? I didn't see it in a quick test.

**Comment by rhaas-edb** [comment]
Fixed (I hope) by 84cb2f6.
